### ISSUE TITLE
Oops! Can not access your website!

### ISSUE THREAD

**Issue by BiDuang** [huizm/huizm.github.io#1]
Does it make sence?

**Comment by huizm** [comment]
It doesn't make senSe. But i'll fix it later. Now I'm going to get some peaches.

**Comment by BiDuang** [comment]
> It doesn't make _senSe_. But I'll fix it later. Now I'm going to get some peaches.

It isn't going to get some chips?

**Comment by BiDuang** [comment]
Cool bruh
